id: AB3EB867E
title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.474892
  last_modified_at: 2022-03-01 03:28:05.474895
