id: AB3EB867E
title: Brief Offering Prayer to Ekajaṭī
type: translation
source_metadata:
  languages:
  - en
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.461236
  last_modified_at: 2022-03-01 03:28:05.461239
