id: AB3EB867E
title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.457920
  last_modified_at: 2022-03-01 03:28:05.457922
