id: AB3EB867E
title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound Guardians'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.469253
  last_modified_at: 2022-03-01 03:28:05.469256
