id: AB3EB867E
title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.459856
  last_modified_at: 2022-03-01 03:28:05.459859
