id: AB3EB867E
title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.481335
  last_modified_at: 2022-03-01 03:28:05.481338
