id: AB3EB867E
title: Brief Offering Prayer to Tsiu Marpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.463167
  last_modified_at: 2022-03-01 03:28:05.463170
