id: AB3EB867E
title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer to Mahākāla
  and Consort'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.482754
  last_modified_at: 2022-03-01 03:28:05.482757
