id: AB3EB867E
title: Petitionary Offering to Norbu Dradül Tsal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.476003
  last_modified_at: 2022-03-01 03:28:05.476006
