id: AB3EB867E
title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to the Glorious
  Guru Mah캐k캐la Pa침jaran캐tha'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.484381
  last_modified_at: 2022-03-01 03:28:05.484384
