id: AB3EB867E
title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.472429
  last_modified_at: 2022-03-01 03:28:05.472432
