id: AB3EB867E
title: Brief Dharmapālas Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.458892
  last_modified_at: 2022-03-01 03:28:05.458895
