id: AB3EB867E
title: Offering to the Five Medicine Sisters, Guardians of the Earth
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:28:05.473552
  last_modified_at: 2022-03-01 03:28:05.473554
